server:
  port: ${SERVER_PORT:7001}

security:
  jwt:
    public-key: classpath:jwt-signing-public-key.txt

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  zipkin:
    base-url: http://${ZIPKIN_HOST:localhost:9411}
    enabled: true
    service:
      name: bookstore-order-service
    message-timeout: 10
  sleuth:
    sampler:
      probability: 1.0
  flyway:
    table: order_service_flyway_history
    baseline-on-migrate: true
    baseline-version: 0.9
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    com.devd.spring.*: DEBUG

management:
  endpoint:
    hystrix:
      stream:
        enabled: true

---

spring:
  profiles: local
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect
    database: PostgreSQL
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    #postgres://bltmfpoo:Zsa0gsSqirnJt4yGqQjYfed1f_Ws2IAP@castor.db.elephantsql.com/bltmfpoo
    #url: jdbc:postgresql://dpg-cib364t9aq03rjltirng-a.oregon-postgres.render.com:5432/bookstore_db_oxkf?user=bookstore_db&password=WcuvAzo6J1iLpvJQ34i1TYgNeXVGJwJ7
    #url: jdbc:postgresql://castor.db.elephantsql.com:5432/bltmfpoo?user=bltmfpoo&password=Zsa0gsSqirnJt4yGqQjYfed1f_Ws2IAP
    url: jdbc:postgresql://ep-floral-leaf-ah3zqqpm-pooler.c-3.us-east-1.aws.neon.tech/Bookstore?user=neondb_owner&password=npg_5yv7FabLrlzs
    username: neondb_owner
    password: npg_5yv7FabLrlzs
---

spring:
  profiles: mysql
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookstore_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: bookstoreDBA
    password: PaSSworD

---

spring:
  profiles: docker
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bookstore-mysql-db:3306/bookstore_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: bookstoreDBA
    password: PaSSworD
